#!/usr/bin/env python
from matlab_bridge.python_interface import PythonInterface

bridge = PythonInterface()
print("Reading from Matlab...")
recv = bridge.read()
print("Received: {}".format(recv))
bridge.send([4, 5, 6])
print("Answer to Matlab sent!")
