#!/usr/bin/env python
from matlab_bridge.python_interface import PythonInterface


def main():
    bridge = PythonInterface()
    i = 0
    while True:
        print "Send python file"
        bridge.send([i, 0, 0])

        print "Read matlab file"
        test = bridge.read()
        print test

        i += 1

if __name__ == '__main__':
    main()
